run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

issues:
  exclude-use-default: false
