apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubesocket
spec:
  selector:
    matchLabels:
      name: kubesocket
  template:
    metadata:
      labels:
        name: kubesocket
    spec:
      hostNetwork: true # CRITICAL: This lets you see the node's traffic
      containers:
      - name: kubesocket
        image: kubesocket:v3
        securityContext:
          privileged: true # CRITICAL: Accessing kubesocket interfaces requires root-level permissions
