apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubetracer
spec:
  selector:
    matchLabels:
      name: kubetracer
  template:
    metadata:
      labels:
        name: kubetracer
    spec:
      hostNetwork: true # CRITICAL: This lets you see the node's traffic
      containers:
      - name: kubetracer
        image: kubetracer:v3
        securityContext:
          privileged: true # CRITICAL: Capturing packets on node NICs requires privileged mode
